const raws = `"escape" | "esc" => CanonicalKey::Escape,
"f1" => CanonicalKey::F1,
"f2" => CanonicalKey::F2,
"f3" => CanonicalKey::F3,
"f4" => CanonicalKey::F4,
"f5" => CanonicalKey::F5,
"f6" => CanonicalKey::F6,
"f7" => CanonicalKey::F7,
"f8" => CanonicalKey::F8,
"f9" => CanonicalKey::F9,
"f10" => CanonicalKey::F10,
"f11" => CanonicalKey::F11,
"f12" => CanonicalKey::F12,
"prtsc" => CanonicalKey::PrtSc,
"scrlk" => CanonicalKey::ScrLk,
"pause" => CanonicalKey::Pause,
"numpad0" => CanonicalKey::NumPad0,
"numpad1" => CanonicalKey::NumPad1,
"numpad2" => CanonicalKey::NumPad2,
"numpad3" => CanonicalKey::NumPad3,
"numpad4" => CanonicalKey::NumPad4,
"numpad5" => CanonicalKey::NumPad5,
"numpad6" => CanonicalKey::NumPad6,
"numpad7" => CanonicalKey::NumPad7,
"numpad8" => CanonicalKey::NumPad8,
"numpad9" => CanonicalKey::NumPad9,
"numlock" => CanonicalKey::NumLock,
"numpaddivide" => CanonicalKey::NumPadDivide,
"numpadmultiply" => CanonicalKey::NumPadMultiply,
"numpadminus" => CanonicalKey::NumPadMinus,
"numpadplus" => CanonicalKey::NumPadPlus,
"numpadseparator" => CanonicalKey::NumPadSeparator,
"numpaddecimal" => CanonicalKey::NumPadDecimal,
"insert" => CanonicalKey::Insert,
"delete" => CanonicalKey::Delete,
"home" => CanonicalKey::Home,
"end" => CanonicalKey::End,
"pageup" => CanonicalKey::PageUp,
"pagedown" => CanonicalKey::PageDown,
"arrowup" => CanonicalKey::ArrowUp,
"arrowdown" => CanonicalKey::ArrowDown,
"arrowleft" => CanonicalKey::ArrowLeft,
"arrowright" => CanonicalKey::ArrowRight,
"tab" => CanonicalKey::Tab,
"capslock" => CanonicalKey::CapsLock,
"lshift" => CanonicalKey::LShift,
"rshift" => CanonicalKey::RShift,
"lctrl" => CanonicalKey::LCtrl,
"rctrl" => CanonicalKey::RCtrl,
"lalt" => CanonicalKey::LAlt,
"ralt" => CanonicalKey::RAlt,
"lmeta" => CanonicalKey::LMeta,
"rmeta" => CanonicalKey::RMeta,
"menu" => CanonicalKey::Menu,
"enter" => CanonicalKey::Enter,
"backspace" => CanonicalKey::Backspace,
"keya" | "a" => CanonicalKey::KeyA,
"keyb" | "b" => CanonicalKey::KeyB,
"keyc" | "c" => CanonicalKey::KeyC,
"keyd" | "d" => CanonicalKey::KeyD,
"keye" | "e" => CanonicalKey::KeyE,
"keyf" | "f" => CanonicalKey::KeyF,
"keyg" | "g" => CanonicalKey::KeyG,
"keyh" | "h" => CanonicalKey::KeyH,
"keyi" | "i" => CanonicalKey::KeyI,
"keyj" | "j" => CanonicalKey::KeyJ,
"keyk" | "k" => CanonicalKey::KeyK,
"keyl" | "l" => CanonicalKey::KeyL,
"keym" | "m" => CanonicalKey::KeyM,
"keyn" | "n" => CanonicalKey::KeyN,
"keyo" | "o" => CanonicalKey::KeyO,
"keyp" | "p" => CanonicalKey::KeyP,
"keyq" | "q" => CanonicalKey::KeyQ,
"keyr" | "r" => CanonicalKey::KeyR,
"keys" | "s" => CanonicalKey::KeyS,
"keyt" | "t" => CanonicalKey::KeyT,
"keyu" | "u" => CanonicalKey::KeyU,
"keyv" | "v" => CanonicalKey::KeyV,
"keyw" | "w" => CanonicalKey::KeyW,
"keyx" | "x" => CanonicalKey::KeyX,
"keyy" | "y" => CanonicalKey::KeyY,
"keyz" | "z" => CanonicalKey::KeyZ,
"num0" | "0" => CanonicalKey::Num0,
"num1" | "1" => CanonicalKey::Num1,
"num2" | "2" => CanonicalKey::Num2,
"num3" | "3" => CanonicalKey::Num3,
"num4" | "4" => CanonicalKey::Num4,
"num5" | "5" => CanonicalKey::Num5,
"num6" | "6" => CanonicalKey::Num6,
"num7" | "7" => CanonicalKey::Num7,
"num8" | "8" => CanonicalKey::Num8,
"num9" | "9" => CanonicalKey::Num9,
"backquote" | "\`" => CanonicalKey::BackQuote,
"minus" | "-" => CanonicalKey::Minus,
"equal" | "=" => CanonicalKey::Equal,
"lbracket" | "[" => CanonicalKey::LBracket,
"rbracket" | "]" => CanonicalKey::RBracket,
"backslash" | "\\\\" => CanonicalKey::BackSlash,
"semicolon" | ";" => CanonicalKey::Semicolon,
"quote" | "'" | "\\"" => CanonicalKey::Quote,
"comma" | "," => CanonicalKey::Comma,
"period" | "." => CanonicalKey::Period,
"slash" | "/" => CanonicalKey::Slash,
"space" | " " => CanonicalKey::Space,`

const keys = raws.split('\n')
    .map(line => line.split(' => ')[0].split(' | '))
    .flat()
    // .map(item => {
    //     if (item === '\'') {
    //         console.log('xxx')
    //         return '\\\''
    //     }
    //     else return item
    // })

console.log(keys.slice(-20))
// console.log(keys)
// console.log(JSON.stringify(keys))
console.log(keys.join(" | "))
