[workspace]
resolver = "2"
members = [
    'crates/tape-core',
    'crates/tape-egui',
    'crates/tape-tauri/backend',
    'crates/tape-node'
]

[workspace.dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0"